"""Add degree and study_year to users table

Revision ID: b589639ac956
Revises: af9b5b92a0cf
Create Date: 2025-09-24 22:12:22.099868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b589639ac956'
down_revision: Union[str, Sequence[str], None] = 'af9b5b92a0cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('degree', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('study_year', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'study_year')
    op.drop_column('users', 'degree')
    # ### end Alembic commands ###
