"""add ai_summaries table

Revision ID: e5cb441e94fa
Revises: 6b2ec812b826
Create Date: 2025-10-29 18:51:06.148563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5cb441e94fa'
down_revision: Union[str, Sequence[str], None] = '6b2ec812b826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_summaries',
    sa.Column('summary_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('generated_by_user_id', sa.UUID(), nullable=False),
    sa.Column('generated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('feedback_count', sa.Integer(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_used', sa.String(length=50), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('sent_to_emails', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('sent_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('summary_id')
    )
    op.create_index(op.f('ix_ai_summaries_event_id'), 'ai_summaries', ['event_id'], unique=False)
    op.create_index(op.f('ix_ai_summaries_generated_by_user_id'), 'ai_summaries', ['generated_by_user_id'], unique=False)
    op.alter_column('feedback', 'is_anonymous',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback', 'is_anonymous',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_ai_summaries_generated_by_user_id'), table_name='ai_summaries')
    op.drop_index(op.f('ix_ai_summaries_event_id'), table_name='ai_summaries')
    op.drop_table('ai_summaries')
    # ### end Alembic commands ###
