server {
    listen 80;
    server_name ennova-events.com www.ennova-events.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name ennova-events.com www.ennova-events.com;

    ssl_certificate     /etc/letsencrypt/live/ennova-events.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ennova-events.com/privkey.pem;

    # ADD THIS ENTIRE BLOCK
    # It tells NGINX to forward any URL starting with /api/
    # to your backend container.
    location /api/ {
        # The 'backend' name comes from your docker-compose.yml file
        

        proxy_pass http://backend:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Origin $http_origin;
    }

    # This existing block serves your frontend application for all other URLs
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
